### ISSUE TITLE
source install is always overwritten by pypi package install

### ISSUE THREAD

**Issue by C-nit** [rdkit/rdkit#5378]
**Describe the bug**
Existing installations from source -at least from conda- are not properly installed as python package. Other python packaging tools such as pip cannot recognize the existing installation.

The symptom is that `pip show rdkit` fails.

**To Reproduce**
This is a conda.yaml that shows the issue:
```yaml
name: rdkit-pypi-overwrites-conda
channels:
  - conda-forge
dependencies:
  - seaborn
  - rdkit
  - pip
  - pip:
      - seaborn
      - rdkit
      # or any other pypi package that has an `install_requires` dependency on rdkit
```

the relevant output showing the difference between a proper install by seaborn and the problematic one by rdkit:
```
...
Installing pip dependencies: \ Ran pip subprocess with arguments:
...
Requirement already satisfied: seaborn in /Users/dow/miniconda3/envs/rdkit-pypi-overwrites-conda/lib/python3.10/site-packages (from -r /Users/dow/tmp/condaenv.03caxs9c.requirements.txt (line 1)) (0.11.2)
Collecting rdkit
  Using cached rdkit-2022.3.3-cp310-cp310-macosx_10_9_x86_64.whl (17.9 MB)
...
Installing collected packages: rdkit
Successfully installed rdkit-2022.3.3

```
**Expected behavior**
After conda installs seaborn and rdkit, it's pip's turn to ensure installation of seaborn and rdkit.
Since the pip dependencies have no version restrictions, the dependencies should be satisfied as is and no installation/upgrade be performed.

For example this works for seaborn, but not for rdkit.

**Additional context**
Note that this issue is not a result of renaming rdkit-pypi to rdkit on pypi. Also installing rdkit-pypi from pip was overwriting the package. Now with the same name we have the chance to prevent that.

Related issues: 
https://github.com/kuelumbus/rdkit-pypi/issues/48
https://github.com/conda-forge/rdkit-feedstock/issues/104
Related PR:
https://github.com/rdkit/rdkit/pull/2690 (that is a mixed bag with discussions also on providing a pypi source distribution, but inevitably also on installing correctly)
